---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfpv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/k8s/tfpv

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
